version: 0.2

env:
  variables:
    key: "S3_BUCKET"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands: #https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/
      - npm install -g newman
      - yum install -y jq

  pre_build:
    commands:
      - cd ./02postman   
      - ./update-postman-env-file.sh   
      - codebuild-breakpoint

  build:
    commands:
      # install node.js v16 to run newman cli tool
      #- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      #- . ~/.nvm/nvm.sh
      #- nvm install 16.0.0
      - echo Build started on `date` from dir `pwd`
      - newman run PetStoreAPI.postman_collection.json --environment PetStoreAPIEnvironment.postman_environment.json -r junit

reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: '02postman/newman' # Location of the reports
